[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package]
name = "rust_os"
version = "0.1.0"
authors = ["0kaguya <carbonc014@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.5.1"

[package.metadata.bootimage]
default-target = "x86_64-rust_os.json"
